#!/bin/bash
# install dependencies
test -d node_modules || npm install
# build
npm run lib-build
# copy readme
cp README.md dist/ion-custom-scrollbar/README.md
# # enter 'dist'
cd dist/ion-custom-scrollbar
# # publish
npm publish
